// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Pulumi.Pihole
{
    /// <summary>
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Pihole = UnMango.Pulumi.Pihole;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var status = new Pihole.AdBlockerStatus("status", new()
    ///     {
    ///         Enabled = true,
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [PiholeResourceType("pihole:index/adBlockerStatus:AdBlockerStatus")]
    public partial class AdBlockerStatus : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether to enable the Pi-hole ad blocker
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;


        /// <summary>
        /// Create a AdBlockerStatus resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AdBlockerStatus(string name, AdBlockerStatusArgs args, CustomResourceOptions? options = null)
            : base("pihole:index/adBlockerStatus:AdBlockerStatus", name, args ?? new AdBlockerStatusArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AdBlockerStatus(string name, Input<string> id, AdBlockerStatusState? state = null, CustomResourceOptions? options = null)
            : base("pihole:index/adBlockerStatus:AdBlockerStatus", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/unmango/pulumi-pihole",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AdBlockerStatus resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AdBlockerStatus Get(string name, Input<string> id, AdBlockerStatusState? state = null, CustomResourceOptions? options = null)
        {
            return new AdBlockerStatus(name, id, state, options);
        }
    }

    public sealed class AdBlockerStatusArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to enable the Pi-hole ad blocker
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        public AdBlockerStatusArgs()
        {
        }
        public static new AdBlockerStatusArgs Empty => new AdBlockerStatusArgs();
    }

    public sealed class AdBlockerStatusState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to enable the Pi-hole ad blocker
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        public AdBlockerStatusState()
        {
        }
        public static new AdBlockerStatusState Empty => new AdBlockerStatusState();
    }
}
