// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Pulumi.Pihole
{
    public static class GetDnsRecords
    {
        /// <summary>
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Pihole = Pulumi.Pihole;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var records = Pihole.GetDnsRecords.Invoke();
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetDnsRecordsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDnsRecordsResult>("pihole:index/getDnsRecords:getDnsRecords", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Pihole = Pulumi.Pihole;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var records = Pihole.GetDnsRecords.Invoke();
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetDnsRecordsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDnsRecordsResult>("pihole:index/getDnsRecords:getDnsRecords", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetDnsRecordsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// List of Pi-hole DNS records
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDnsRecordsRecordResult> Records;

        [OutputConstructor]
        private GetDnsRecordsResult(
            string id,

            ImmutableArray<Outputs.GetDnsRecordsRecordResult> records)
        {
            Id = id;
            Records = records;
        }
    }
}
