// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.unmango.pulumi.pihole;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;


public final class AdBlockerStatusArgs extends com.pulumi.resources.ResourceArgs {

    public static final AdBlockerStatusArgs Empty = new AdBlockerStatusArgs();

    /**
     * Whether to enable the Pi-hole ad blocker
     * 
     */
    @Import(name="enabled", required=true)
    private Output<Boolean> enabled;

    /**
     * @return Whether to enable the Pi-hole ad blocker
     * 
     */
    public Output<Boolean> enabled() {
        return this.enabled;
    }

    private AdBlockerStatusArgs() {}

    private AdBlockerStatusArgs(AdBlockerStatusArgs $) {
        this.enabled = $.enabled;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AdBlockerStatusArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AdBlockerStatusArgs $;

        public Builder() {
            $ = new AdBlockerStatusArgs();
        }

        public Builder(AdBlockerStatusArgs defaults) {
            $ = new AdBlockerStatusArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param enabled Whether to enable the Pi-hole ad blocker
         * 
         * @return builder
         * 
         */
        public Builder enabled(Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Whether to enable the Pi-hole ad blocker
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        public AdBlockerStatusArgs build() {
            $.enabled = Objects.requireNonNull($.enabled, "expected parameter 'enabled' to be non-null");
            return $;
        }
    }

}
