// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.unmango.pulumi.pihole;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.unmango.pulumi.pihole.AdBlockerStatusArgs;
import com.unmango.pulumi.pihole.Utilities;
import com.unmango.pulumi.pihole.inputs.AdBlockerStatusState;
import java.lang.Boolean;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.pihole.AdBlockerStatus;
 * import com.pulumi.pihole.AdBlockerStatusArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var status = new AdBlockerStatus(&#34;status&#34;, AdBlockerStatusArgs.builder()        
 *             .enabled(true)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 */
@ResourceType(type="pihole:index/adBlockerStatus:AdBlockerStatus")
public class AdBlockerStatus extends com.pulumi.resources.CustomResource {
    /**
     * Whether to enable the Pi-hole ad blocker
     * 
     */
    @Export(name="enabled", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> enabled;

    /**
     * @return Whether to enable the Pi-hole ad blocker
     * 
     */
    public Output<Boolean> enabled() {
        return this.enabled;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public AdBlockerStatus(String name) {
        this(name, AdBlockerStatusArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public AdBlockerStatus(String name, AdBlockerStatusArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public AdBlockerStatus(String name, AdBlockerStatusArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pihole:index/adBlockerStatus:AdBlockerStatus", name, args == null ? AdBlockerStatusArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private AdBlockerStatus(String name, Output<String> id, @Nullable AdBlockerStatusState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("pihole:index/adBlockerStatus:AdBlockerStatus", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static AdBlockerStatus get(String name, Output<String> id, @Nullable AdBlockerStatusState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new AdBlockerStatus(name, id, state, options);
    }
}
