// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.unmango.pulumi.pihole;

import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("pihole");
/**
 * Experimental: Pi-hole API token. Conflicts with `password`.
 * 
 */
    public Optional<String> apiToken() {
        return Codegen.stringProp("apiToken").config(config).env("PIHOLE_API_TOKEN").get();
    }
/**
 * CA file to connect to Pi-hole with TLS
 * 
 */
    public Optional<String> caFile() {
        return Codegen.stringProp("caFile").config(config).env("PIHOLE_CA_FILE").get();
    }
/**
 * The admin password used to login to the admin dashboard. Conflicts with `api_token`.
 * 
 */
    public Optional<String> password() {
        return Codegen.stringProp("password").config(config).env("PIHOLE_PASSWORD").get();
    }
/**
 * URL where Pi-hole is deployed
 * 
 */
    public Optional<String> url() {
        return Codegen.stringProp("url").config(config).env("PIHOLE_URL").get();
    }
}
