// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.unmango.pulumi.pihole.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CnameRecordState extends com.pulumi.resources.ResourceArgs {

    public static final CnameRecordState Empty = new CnameRecordState();

    /**
     * Domain to create a CNAME record for
     * 
     */
    @Import(name="domain")
    private @Nullable Output<String> domain;

    /**
     * @return Domain to create a CNAME record for
     * 
     */
    public Optional<Output<String>> domain() {
        return Optional.ofNullable(this.domain);
    }

    /**
     * Value of the CNAME record where traffic will be directed to from the configured domain value
     * 
     */
    @Import(name="target")
    private @Nullable Output<String> target;

    /**
     * @return Value of the CNAME record where traffic will be directed to from the configured domain value
     * 
     */
    public Optional<Output<String>> target() {
        return Optional.ofNullable(this.target);
    }

    private CnameRecordState() {}

    private CnameRecordState(CnameRecordState $) {
        this.domain = $.domain;
        this.target = $.target;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CnameRecordState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CnameRecordState $;

        public Builder() {
            $ = new CnameRecordState();
        }

        public Builder(CnameRecordState defaults) {
            $ = new CnameRecordState(Objects.requireNonNull(defaults));
        }

        /**
         * @param domain Domain to create a CNAME record for
         * 
         * @return builder
         * 
         */
        public Builder domain(@Nullable Output<String> domain) {
            $.domain = domain;
            return this;
        }

        /**
         * @param domain Domain to create a CNAME record for
         * 
         * @return builder
         * 
         */
        public Builder domain(String domain) {
            return domain(Output.of(domain));
        }

        /**
         * @param target Value of the CNAME record where traffic will be directed to from the configured domain value
         * 
         * @return builder
         * 
         */
        public Builder target(@Nullable Output<String> target) {
            $.target = target;
            return this;
        }

        /**
         * @param target Value of the CNAME record where traffic will be directed to from the configured domain value
         * 
         * @return builder
         * 
         */
        public Builder target(String target) {
            return target(Output.of(target));
        }

        public CnameRecordState build() {
            return $;
        }
    }

}
