// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Pulumi.Pihole.Outputs
{

    [OutputType]
    public sealed class GetCnameRecordsRecordResult
    {
        public readonly string Domain;
        public readonly string Target;

        [OutputConstructor]
        private GetCnameRecordsRecordResult(
            string domain,

            string target)
        {
            Domain = domain;
            Target = target;
        }
    }
}
