// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Pulumi.Pihole.Outputs
{

    [OutputType]
    public sealed class GetDomainsDomainResult
    {
        public readonly string Comment;
        public readonly string Domain;
        public readonly bool Enabled;
        public readonly ImmutableArray<int> GroupIds;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Filter on allowed or denied domains. Must be either 'allow' or 'deny'.
        /// </summary>
        public readonly string Type;
        public readonly bool Wildcard;

        [OutputConstructor]
        private GetDomainsDomainResult(
            string comment,

            string domain,

            bool enabled,

            ImmutableArray<int> groupIds,

            int id,

            string type,

            bool wildcard)
        {
            Comment = comment;
            Domain = domain;
            Enabled = enabled;
            GroupIds = groupIds;
            Id = id;
            Type = type;
            Wildcard = wildcard;
        }
    }
}
