// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Pulumi.Pihole.Outputs
{

    [OutputType]
    public sealed class GetDomainsDomainResult
    {
        /// <summary>
        /// Comments associated with the domain
        /// </summary>
        public readonly string Comment;
        /// <summary>
        /// Domain
        /// </summary>
        public readonly string Domain;
        /// <summary>
        /// Whether the domain rule is enabled
        /// </summary>
        public readonly bool Enabled;
        /// <summary>
        /// Groups to which the domain is associated
        /// </summary>
        public readonly ImmutableArray<int> GroupIds;
        /// <summary>
        /// Domain ID
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// Whether the doamin is on the allow or deny list
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Whether the domain should be interpreted using a wildcard parser
        /// </summary>
        public readonly bool Wildcard;

        [OutputConstructor]
        private GetDomainsDomainResult(
            string comment,

            string domain,

            bool enabled,

            ImmutableArray<int> groupIds,

            int id,

            string type,

            bool wildcard)
        {
            Comment = comment;
            Domain = domain;
            Enabled = enabled;
            GroupIds = groupIds;
            Id = id;
            Type = type;
            Wildcard = wildcard;
        }
    }
}
