// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.Pulumi.Pihole.Outputs
{

    [OutputType]
    public sealed class GetGroupsGroupResult
    {
        public readonly string Description;
        public readonly bool Enabled;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly int Id;
        public readonly string Name;

        [OutputConstructor]
        private GetGroupsGroupResult(
            string description,

            bool enabled,

            int id,

            string name)
        {
            Description = description;
            Enabled = enabled;
            Id = id;
            Name = name;
        }
    }
}
