# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

apiToken: Optional[str]
"""
Experimental: Pi-hole API token. Conflicts with `password`.
"""

caFile: Optional[str]
"""
CA file to connect to Pi-hole with TLS
"""

password: Optional[str]
"""
The admin password used to login to the admin dashboard. Conflicts with `api_token`.
"""

url: Optional[str]
"""
URL where Pi-hole is deployed
"""

