// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.unmango.pulumi.pihole.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetCnameRecordsRecord {
    private String domain;
    private String target;

    private GetCnameRecordsRecord() {}
    public String domain() {
        return this.domain;
    }
    public String target() {
        return this.target;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCnameRecordsRecord defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String domain;
        private String target;
        public Builder() {}
        public Builder(GetCnameRecordsRecord defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.domain = defaults.domain;
    	      this.target = defaults.target;
        }

        @CustomType.Setter
        public Builder domain(String domain) {
            this.domain = Objects.requireNonNull(domain);
            return this;
        }
        @CustomType.Setter
        public Builder target(String target) {
            this.target = Objects.requireNonNull(target);
            return this;
        }
        public GetCnameRecordsRecord build() {
            final var _resultValue = new GetCnameRecordsRecord();
            _resultValue.domain = domain;
            _resultValue.target = target;
            return _resultValue;
        }
    }
}
