// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.unmango.pulumi.pihole.outputs;

import com.pulumi.core.annotations.CustomType;
import com.unmango.pulumi.pihole.outputs.GetDnsRecordsRecord;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetDnsRecordsResult {
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return List of Pi-hole DNS records
     * 
     */
    private List<GetDnsRecordsRecord> records;

    private GetDnsRecordsResult() {}
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return List of Pi-hole DNS records
     * 
     */
    public List<GetDnsRecordsRecord> records() {
        return this.records;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDnsRecordsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private List<GetDnsRecordsRecord> records;
        public Builder() {}
        public Builder(GetDnsRecordsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.records = defaults.records;
        }

        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder records(List<GetDnsRecordsRecord> records) {
            this.records = Objects.requireNonNull(records);
            return this;
        }
        public Builder records(GetDnsRecordsRecord... records) {
            return records(List.of(records));
        }
        public GetDnsRecordsResult build() {
            final var _resultValue = new GetDnsRecordsResult();
            _resultValue.id = id;
            _resultValue.records = records;
            return _resultValue;
        }
    }
}
