// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pihole

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/unmango/pulumi-pihole/sdk/go/pihole/internal"
)

var _ = internal.GetEnvOrDefault

type GetCnameRecordsRecord struct {
	// CNAME record domain
	Domain string `pulumi:"domain"`
	// CNAME target value where traffic is routed to from the domain
	Target string `pulumi:"target"`
}

// GetCnameRecordsRecordInput is an input type that accepts GetCnameRecordsRecordArgs and GetCnameRecordsRecordOutput values.
// You can construct a concrete instance of `GetCnameRecordsRecordInput` via:
//
//	GetCnameRecordsRecordArgs{...}
type GetCnameRecordsRecordInput interface {
	pulumi.Input

	ToGetCnameRecordsRecordOutput() GetCnameRecordsRecordOutput
	ToGetCnameRecordsRecordOutputWithContext(context.Context) GetCnameRecordsRecordOutput
}

type GetCnameRecordsRecordArgs struct {
	// CNAME record domain
	Domain pulumi.StringInput `pulumi:"domain"`
	// CNAME target value where traffic is routed to from the domain
	Target pulumi.StringInput `pulumi:"target"`
}

func (GetCnameRecordsRecordArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCnameRecordsRecord)(nil)).Elem()
}

func (i GetCnameRecordsRecordArgs) ToGetCnameRecordsRecordOutput() GetCnameRecordsRecordOutput {
	return i.ToGetCnameRecordsRecordOutputWithContext(context.Background())
}

func (i GetCnameRecordsRecordArgs) ToGetCnameRecordsRecordOutputWithContext(ctx context.Context) GetCnameRecordsRecordOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetCnameRecordsRecordOutput)
}

// GetCnameRecordsRecordArrayInput is an input type that accepts GetCnameRecordsRecordArray and GetCnameRecordsRecordArrayOutput values.
// You can construct a concrete instance of `GetCnameRecordsRecordArrayInput` via:
//
//	GetCnameRecordsRecordArray{ GetCnameRecordsRecordArgs{...} }
type GetCnameRecordsRecordArrayInput interface {
	pulumi.Input

	ToGetCnameRecordsRecordArrayOutput() GetCnameRecordsRecordArrayOutput
	ToGetCnameRecordsRecordArrayOutputWithContext(context.Context) GetCnameRecordsRecordArrayOutput
}

type GetCnameRecordsRecordArray []GetCnameRecordsRecordInput

func (GetCnameRecordsRecordArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetCnameRecordsRecord)(nil)).Elem()
}

func (i GetCnameRecordsRecordArray) ToGetCnameRecordsRecordArrayOutput() GetCnameRecordsRecordArrayOutput {
	return i.ToGetCnameRecordsRecordArrayOutputWithContext(context.Background())
}

func (i GetCnameRecordsRecordArray) ToGetCnameRecordsRecordArrayOutputWithContext(ctx context.Context) GetCnameRecordsRecordArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetCnameRecordsRecordArrayOutput)
}

type GetCnameRecordsRecordOutput struct{ *pulumi.OutputState }

func (GetCnameRecordsRecordOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCnameRecordsRecord)(nil)).Elem()
}

func (o GetCnameRecordsRecordOutput) ToGetCnameRecordsRecordOutput() GetCnameRecordsRecordOutput {
	return o
}

func (o GetCnameRecordsRecordOutput) ToGetCnameRecordsRecordOutputWithContext(ctx context.Context) GetCnameRecordsRecordOutput {
	return o
}

// CNAME record domain
func (o GetCnameRecordsRecordOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v GetCnameRecordsRecord) string { return v.Domain }).(pulumi.StringOutput)
}

// CNAME target value where traffic is routed to from the domain
func (o GetCnameRecordsRecordOutput) Target() pulumi.StringOutput {
	return o.ApplyT(func(v GetCnameRecordsRecord) string { return v.Target }).(pulumi.StringOutput)
}

type GetCnameRecordsRecordArrayOutput struct{ *pulumi.OutputState }

func (GetCnameRecordsRecordArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetCnameRecordsRecord)(nil)).Elem()
}

func (o GetCnameRecordsRecordArrayOutput) ToGetCnameRecordsRecordArrayOutput() GetCnameRecordsRecordArrayOutput {
	return o
}

func (o GetCnameRecordsRecordArrayOutput) ToGetCnameRecordsRecordArrayOutputWithContext(ctx context.Context) GetCnameRecordsRecordArrayOutput {
	return o
}

func (o GetCnameRecordsRecordArrayOutput) Index(i pulumi.IntInput) GetCnameRecordsRecordOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetCnameRecordsRecord {
		return vs[0].([]GetCnameRecordsRecord)[vs[1].(int)]
	}).(GetCnameRecordsRecordOutput)
}

type GetDnsRecordsRecord struct {
	// DNS record domain
	Domain string `pulumi:"domain"`
	// IP address where traffic is routed to from the DNS record domain
	Ip string `pulumi:"ip"`
}

// GetDnsRecordsRecordInput is an input type that accepts GetDnsRecordsRecordArgs and GetDnsRecordsRecordOutput values.
// You can construct a concrete instance of `GetDnsRecordsRecordInput` via:
//
//	GetDnsRecordsRecordArgs{...}
type GetDnsRecordsRecordInput interface {
	pulumi.Input

	ToGetDnsRecordsRecordOutput() GetDnsRecordsRecordOutput
	ToGetDnsRecordsRecordOutputWithContext(context.Context) GetDnsRecordsRecordOutput
}

type GetDnsRecordsRecordArgs struct {
	// DNS record domain
	Domain pulumi.StringInput `pulumi:"domain"`
	// IP address where traffic is routed to from the DNS record domain
	Ip pulumi.StringInput `pulumi:"ip"`
}

func (GetDnsRecordsRecordArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDnsRecordsRecord)(nil)).Elem()
}

func (i GetDnsRecordsRecordArgs) ToGetDnsRecordsRecordOutput() GetDnsRecordsRecordOutput {
	return i.ToGetDnsRecordsRecordOutputWithContext(context.Background())
}

func (i GetDnsRecordsRecordArgs) ToGetDnsRecordsRecordOutputWithContext(ctx context.Context) GetDnsRecordsRecordOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetDnsRecordsRecordOutput)
}

// GetDnsRecordsRecordArrayInput is an input type that accepts GetDnsRecordsRecordArray and GetDnsRecordsRecordArrayOutput values.
// You can construct a concrete instance of `GetDnsRecordsRecordArrayInput` via:
//
//	GetDnsRecordsRecordArray{ GetDnsRecordsRecordArgs{...} }
type GetDnsRecordsRecordArrayInput interface {
	pulumi.Input

	ToGetDnsRecordsRecordArrayOutput() GetDnsRecordsRecordArrayOutput
	ToGetDnsRecordsRecordArrayOutputWithContext(context.Context) GetDnsRecordsRecordArrayOutput
}

type GetDnsRecordsRecordArray []GetDnsRecordsRecordInput

func (GetDnsRecordsRecordArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetDnsRecordsRecord)(nil)).Elem()
}

func (i GetDnsRecordsRecordArray) ToGetDnsRecordsRecordArrayOutput() GetDnsRecordsRecordArrayOutput {
	return i.ToGetDnsRecordsRecordArrayOutputWithContext(context.Background())
}

func (i GetDnsRecordsRecordArray) ToGetDnsRecordsRecordArrayOutputWithContext(ctx context.Context) GetDnsRecordsRecordArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetDnsRecordsRecordArrayOutput)
}

type GetDnsRecordsRecordOutput struct{ *pulumi.OutputState }

func (GetDnsRecordsRecordOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDnsRecordsRecord)(nil)).Elem()
}

func (o GetDnsRecordsRecordOutput) ToGetDnsRecordsRecordOutput() GetDnsRecordsRecordOutput {
	return o
}

func (o GetDnsRecordsRecordOutput) ToGetDnsRecordsRecordOutputWithContext(ctx context.Context) GetDnsRecordsRecordOutput {
	return o
}

// DNS record domain
func (o GetDnsRecordsRecordOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v GetDnsRecordsRecord) string { return v.Domain }).(pulumi.StringOutput)
}

// IP address where traffic is routed to from the DNS record domain
func (o GetDnsRecordsRecordOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v GetDnsRecordsRecord) string { return v.Ip }).(pulumi.StringOutput)
}

type GetDnsRecordsRecordArrayOutput struct{ *pulumi.OutputState }

func (GetDnsRecordsRecordArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetDnsRecordsRecord)(nil)).Elem()
}

func (o GetDnsRecordsRecordArrayOutput) ToGetDnsRecordsRecordArrayOutput() GetDnsRecordsRecordArrayOutput {
	return o
}

func (o GetDnsRecordsRecordArrayOutput) ToGetDnsRecordsRecordArrayOutputWithContext(ctx context.Context) GetDnsRecordsRecordArrayOutput {
	return o
}

func (o GetDnsRecordsRecordArrayOutput) Index(i pulumi.IntInput) GetDnsRecordsRecordOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetDnsRecordsRecord {
		return vs[0].([]GetDnsRecordsRecord)[vs[1].(int)]
	}).(GetDnsRecordsRecordOutput)
}

type GetDomainsDomain struct {
	// Comments associated with the domain
	Comment string `pulumi:"comment"`
	// Domain
	Domain string `pulumi:"domain"`
	// Whether the domain rule is enabled
	Enabled bool `pulumi:"enabled"`
	// Groups to which the domain is associated
	GroupIds []int `pulumi:"groupIds"`
	// Domain ID
	Id int `pulumi:"id"`
	// Whether the doamin is on the allow or deny list
	Type string `pulumi:"type"`
	// Whether the domain should be interpreted using a wildcard parser
	Wildcard bool `pulumi:"wildcard"`
}

// GetDomainsDomainInput is an input type that accepts GetDomainsDomainArgs and GetDomainsDomainOutput values.
// You can construct a concrete instance of `GetDomainsDomainInput` via:
//
//	GetDomainsDomainArgs{...}
type GetDomainsDomainInput interface {
	pulumi.Input

	ToGetDomainsDomainOutput() GetDomainsDomainOutput
	ToGetDomainsDomainOutputWithContext(context.Context) GetDomainsDomainOutput
}

type GetDomainsDomainArgs struct {
	// Comments associated with the domain
	Comment pulumi.StringInput `pulumi:"comment"`
	// Domain
	Domain pulumi.StringInput `pulumi:"domain"`
	// Whether the domain rule is enabled
	Enabled pulumi.BoolInput `pulumi:"enabled"`
	// Groups to which the domain is associated
	GroupIds pulumi.IntArrayInput `pulumi:"groupIds"`
	// Domain ID
	Id pulumi.IntInput `pulumi:"id"`
	// Whether the doamin is on the allow or deny list
	Type pulumi.StringInput `pulumi:"type"`
	// Whether the domain should be interpreted using a wildcard parser
	Wildcard pulumi.BoolInput `pulumi:"wildcard"`
}

func (GetDomainsDomainArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDomainsDomain)(nil)).Elem()
}

func (i GetDomainsDomainArgs) ToGetDomainsDomainOutput() GetDomainsDomainOutput {
	return i.ToGetDomainsDomainOutputWithContext(context.Background())
}

func (i GetDomainsDomainArgs) ToGetDomainsDomainOutputWithContext(ctx context.Context) GetDomainsDomainOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetDomainsDomainOutput)
}

// GetDomainsDomainArrayInput is an input type that accepts GetDomainsDomainArray and GetDomainsDomainArrayOutput values.
// You can construct a concrete instance of `GetDomainsDomainArrayInput` via:
//
//	GetDomainsDomainArray{ GetDomainsDomainArgs{...} }
type GetDomainsDomainArrayInput interface {
	pulumi.Input

	ToGetDomainsDomainArrayOutput() GetDomainsDomainArrayOutput
	ToGetDomainsDomainArrayOutputWithContext(context.Context) GetDomainsDomainArrayOutput
}

type GetDomainsDomainArray []GetDomainsDomainInput

func (GetDomainsDomainArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetDomainsDomain)(nil)).Elem()
}

func (i GetDomainsDomainArray) ToGetDomainsDomainArrayOutput() GetDomainsDomainArrayOutput {
	return i.ToGetDomainsDomainArrayOutputWithContext(context.Background())
}

func (i GetDomainsDomainArray) ToGetDomainsDomainArrayOutputWithContext(ctx context.Context) GetDomainsDomainArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetDomainsDomainArrayOutput)
}

type GetDomainsDomainOutput struct{ *pulumi.OutputState }

func (GetDomainsDomainOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDomainsDomain)(nil)).Elem()
}

func (o GetDomainsDomainOutput) ToGetDomainsDomainOutput() GetDomainsDomainOutput {
	return o
}

func (o GetDomainsDomainOutput) ToGetDomainsDomainOutputWithContext(ctx context.Context) GetDomainsDomainOutput {
	return o
}

// Comments associated with the domain
func (o GetDomainsDomainOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v GetDomainsDomain) string { return v.Comment }).(pulumi.StringOutput)
}

// Domain
func (o GetDomainsDomainOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v GetDomainsDomain) string { return v.Domain }).(pulumi.StringOutput)
}

// Whether the domain rule is enabled
func (o GetDomainsDomainOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDomainsDomain) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// Groups to which the domain is associated
func (o GetDomainsDomainOutput) GroupIds() pulumi.IntArrayOutput {
	return o.ApplyT(func(v GetDomainsDomain) []int { return v.GroupIds }).(pulumi.IntArrayOutput)
}

// Domain ID
func (o GetDomainsDomainOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v GetDomainsDomain) int { return v.Id }).(pulumi.IntOutput)
}

// Whether the doamin is on the allow or deny list
func (o GetDomainsDomainOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetDomainsDomain) string { return v.Type }).(pulumi.StringOutput)
}

// Whether the domain should be interpreted using a wildcard parser
func (o GetDomainsDomainOutput) Wildcard() pulumi.BoolOutput {
	return o.ApplyT(func(v GetDomainsDomain) bool { return v.Wildcard }).(pulumi.BoolOutput)
}

type GetDomainsDomainArrayOutput struct{ *pulumi.OutputState }

func (GetDomainsDomainArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetDomainsDomain)(nil)).Elem()
}

func (o GetDomainsDomainArrayOutput) ToGetDomainsDomainArrayOutput() GetDomainsDomainArrayOutput {
	return o
}

func (o GetDomainsDomainArrayOutput) ToGetDomainsDomainArrayOutputWithContext(ctx context.Context) GetDomainsDomainArrayOutput {
	return o
}

func (o GetDomainsDomainArrayOutput) Index(i pulumi.IntInput) GetDomainsDomainOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetDomainsDomain {
		return vs[0].([]GetDomainsDomain)[vs[1].(int)]
	}).(GetDomainsDomainOutput)
}

type GetGroupsGroup struct {
	// Group description
	Description string `pulumi:"description"`
	// Whether the group is enabled
	Enabled bool `pulumi:"enabled"`
	// Group ID
	Id int `pulumi:"id"`
	// Name of the group
	Name string `pulumi:"name"`
}

// GetGroupsGroupInput is an input type that accepts GetGroupsGroupArgs and GetGroupsGroupOutput values.
// You can construct a concrete instance of `GetGroupsGroupInput` via:
//
//	GetGroupsGroupArgs{...}
type GetGroupsGroupInput interface {
	pulumi.Input

	ToGetGroupsGroupOutput() GetGroupsGroupOutput
	ToGetGroupsGroupOutputWithContext(context.Context) GetGroupsGroupOutput
}

type GetGroupsGroupArgs struct {
	// Group description
	Description pulumi.StringInput `pulumi:"description"`
	// Whether the group is enabled
	Enabled pulumi.BoolInput `pulumi:"enabled"`
	// Group ID
	Id pulumi.IntInput `pulumi:"id"`
	// Name of the group
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetGroupsGroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGroupsGroup)(nil)).Elem()
}

func (i GetGroupsGroupArgs) ToGetGroupsGroupOutput() GetGroupsGroupOutput {
	return i.ToGetGroupsGroupOutputWithContext(context.Background())
}

func (i GetGroupsGroupArgs) ToGetGroupsGroupOutputWithContext(ctx context.Context) GetGroupsGroupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetGroupsGroupOutput)
}

// GetGroupsGroupArrayInput is an input type that accepts GetGroupsGroupArray and GetGroupsGroupArrayOutput values.
// You can construct a concrete instance of `GetGroupsGroupArrayInput` via:
//
//	GetGroupsGroupArray{ GetGroupsGroupArgs{...} }
type GetGroupsGroupArrayInput interface {
	pulumi.Input

	ToGetGroupsGroupArrayOutput() GetGroupsGroupArrayOutput
	ToGetGroupsGroupArrayOutputWithContext(context.Context) GetGroupsGroupArrayOutput
}

type GetGroupsGroupArray []GetGroupsGroupInput

func (GetGroupsGroupArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetGroupsGroup)(nil)).Elem()
}

func (i GetGroupsGroupArray) ToGetGroupsGroupArrayOutput() GetGroupsGroupArrayOutput {
	return i.ToGetGroupsGroupArrayOutputWithContext(context.Background())
}

func (i GetGroupsGroupArray) ToGetGroupsGroupArrayOutputWithContext(ctx context.Context) GetGroupsGroupArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetGroupsGroupArrayOutput)
}

type GetGroupsGroupOutput struct{ *pulumi.OutputState }

func (GetGroupsGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetGroupsGroup)(nil)).Elem()
}

func (o GetGroupsGroupOutput) ToGetGroupsGroupOutput() GetGroupsGroupOutput {
	return o
}

func (o GetGroupsGroupOutput) ToGetGroupsGroupOutputWithContext(ctx context.Context) GetGroupsGroupOutput {
	return o
}

// Group description
func (o GetGroupsGroupOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupsGroup) string { return v.Description }).(pulumi.StringOutput)
}

// Whether the group is enabled
func (o GetGroupsGroupOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v GetGroupsGroup) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// Group ID
func (o GetGroupsGroupOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v GetGroupsGroup) int { return v.Id }).(pulumi.IntOutput)
}

// Name of the group
func (o GetGroupsGroupOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetGroupsGroup) string { return v.Name }).(pulumi.StringOutput)
}

type GetGroupsGroupArrayOutput struct{ *pulumi.OutputState }

func (GetGroupsGroupArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetGroupsGroup)(nil)).Elem()
}

func (o GetGroupsGroupArrayOutput) ToGetGroupsGroupArrayOutput() GetGroupsGroupArrayOutput {
	return o
}

func (o GetGroupsGroupArrayOutput) ToGetGroupsGroupArrayOutputWithContext(ctx context.Context) GetGroupsGroupArrayOutput {
	return o
}

func (o GetGroupsGroupArrayOutput) Index(i pulumi.IntInput) GetGroupsGroupOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetGroupsGroup {
		return vs[0].([]GetGroupsGroup)[vs[1].(int)]
	}).(GetGroupsGroupOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GetCnameRecordsRecordInput)(nil)).Elem(), GetCnameRecordsRecordArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetCnameRecordsRecordArrayInput)(nil)).Elem(), GetCnameRecordsRecordArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetDnsRecordsRecordInput)(nil)).Elem(), GetDnsRecordsRecordArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetDnsRecordsRecordArrayInput)(nil)).Elem(), GetDnsRecordsRecordArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetDomainsDomainInput)(nil)).Elem(), GetDomainsDomainArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetDomainsDomainArrayInput)(nil)).Elem(), GetDomainsDomainArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetGroupsGroupInput)(nil)).Elem(), GetGroupsGroupArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetGroupsGroupArrayInput)(nil)).Elem(), GetGroupsGroupArray{})
	pulumi.RegisterOutputType(GetCnameRecordsRecordOutput{})
	pulumi.RegisterOutputType(GetCnameRecordsRecordArrayOutput{})
	pulumi.RegisterOutputType(GetDnsRecordsRecordOutput{})
	pulumi.RegisterOutputType(GetDnsRecordsRecordArrayOutput{})
	pulumi.RegisterOutputType(GetDomainsDomainOutput{})
	pulumi.RegisterOutputType(GetDomainsDomainArrayOutput{})
	pulumi.RegisterOutputType(GetGroupsGroupOutput{})
	pulumi.RegisterOutputType(GetGroupsGroupArrayOutput{})
}
