name: Automated Upgrades

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Call upgrade provider action
        uses: pulumi/pulumi-upgrade-provider-action@v0.0.11
