// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as pihole from "@pulumi/pihole";
 *
 * const records = pihole.getCnameRecords({});
 * ```
 */
export function getCnameRecords(opts?: pulumi.InvokeOptions): Promise<GetCnameRecordsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pihole:index/getCnameRecords:getCnameRecords", {
    }, opts);
}

/**
 * A collection of values returned by getCnameRecords.
 */
export interface GetCnameRecordsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * List of CNAME Pi-hole records
     */
    readonly records: outputs.GetCnameRecordsRecord[];
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as pihole from "@pulumi/pihole";
 *
 * const records = pihole.getCnameRecords({});
 * ```
 */
export function getCnameRecordsOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetCnameRecordsResult> {
    return pulumi.output(getCnameRecords(opts))
}
