// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as pihole from "@pulumi/pihole";
 *
 * const records = pihole.getDnsRecords({});
 * ```
 */
export function getDnsRecords(opts?: pulumi.InvokeOptions): Promise<GetDnsRecordsResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pihole:index/getDnsRecords:getDnsRecords", {
    }, opts);
}

/**
 * A collection of values returned by getDnsRecords.
 */
export interface GetDnsRecordsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * List of Pi-hole DNS records
     */
    readonly records: outputs.GetDnsRecordsRecord[];
}
/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as pihole from "@pulumi/pihole";
 *
 * const records = pihole.getDnsRecords({});
 * ```
 */
export function getDnsRecordsOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetDnsRecordsResult> {
    return pulumi.output(getDnsRecords(opts))
}
