// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the pihole package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'pihole';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * Experimental: Pi-hole API token. Conflicts with `password`.
     */
    public readonly apiToken!: pulumi.Output<string | undefined>;
    /**
     * CA file to connect to Pi-hole with TLS
     */
    public readonly caFile!: pulumi.Output<string | undefined>;
    /**
     * The admin password used to login to the admin dashboard. Conflicts with `apiToken`.
     */
    public readonly password!: pulumi.Output<string | undefined>;
    /**
     * URL where Pi-hole is deployed
     */
    public readonly url!: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["apiToken"] = (args ? args.apiToken : undefined) ?? utilities.getEnv("PIHOLE_API_TOKEN");
            resourceInputs["caFile"] = (args ? args.caFile : undefined) ?? utilities.getEnv("PIHOLE_CA_FILE");
            resourceInputs["password"] = (args ? args.password : undefined) ?? utilities.getEnv("PIHOLE_PASSWORD");
            resourceInputs["url"] = (args ? args.url : undefined) ?? utilities.getEnv("PIHOLE_URL");
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Experimental: Pi-hole API token. Conflicts with `password`.
     */
    apiToken?: pulumi.Input<string>;
    /**
     * CA file to connect to Pi-hole with TLS
     */
    caFile?: pulumi.Input<string>;
    /**
     * The admin password used to login to the admin dashboard. Conflicts with `apiToken`.
     */
    password?: pulumi.Input<string>;
    /**
     * URL where Pi-hole is deployed
     */
    url?: pulumi.Input<string>;
}
